name = "AoC2025"
version = "0.1.0"
defaultTargets = ["aoc2025"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.24.1"

[[lean_lib]]
name = "AoC2025"

[[lean_exe]]
name = "aoc2025"
root = "Main"
